---
core:
   num_workers: 100


inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "/home/tidadini/Desktop/Python_Projects/Network_Automation/Nornir/hosts.yaml"
        group_file: "/home/tidadini/Desktop/Python_Projects/Network_Automation/Nornir/groups.yaml"
        defaults_file: "/home/tidadini/Desktop/Python_Projects/Network_Automation/Nornir/defaults.yaml"

